# Generated by Django 5.0.6 on 2024-07-10 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0002_remove_customuser_college_alter_customuser_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='image',
        ),
    ]
