# Generated by Django 5.0.6 on 2024-07-13 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0005_alter_problemdetail_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usercode', models.TextField(max_length=10000)),
                ('Language', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='problemdetail',
            name='difficulty',
            field=models.CharField(max_length=10),
        ),
    ]
