# Generated by Django 5.0.6 on 2024-07-13 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth2', '0003_remove_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Problems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_title', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProblemDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_description', models.TextField(max_length=10000)),
                ('difficulty', models.IntegerField(max_length=2)),
                ('testcases', models.TextField(max_length=3000)),
                ('solution', models.TextField(max_length=3000)),
                ('problem', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth2.problems')),
            ],
        ),
    ]
